### PR TITLE
Add support for aarch64 and ppc64le

### PR DESCRIPTION
**Pull request by awvwgk**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* ~~Reset the build number to `0` (if the version changed)~~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by certik** [comment]
Looks good. How did you get all the other changes in your own commit? I usually let the linter push those changes in the PR that I open.

**Comment by awvwgk** [comment]
You can add the architectures to the `conda_forge.yml` and than rerender with conda smithy.
```yaml
provider:
  linux_ppc64le: default
  linux_aarch64: default
```

**Comment by certik** [comment]
You rerendered locally in your terminal?

**Comment by awvwgk** [comment]
Yeah, I have a local conda-build / conda-smithy setup for this purpose.

Here is the docs on the CI support:
https://conda-forge.org/docs/maintainer/conda_forge_yml.html#provider

**Comment by certik** [comment]
Nice! So far I only used the command in the comment (I am not going to type it so that it does not render by accident) and it renders automatically as a new commit in the PR.

**Comment by awvwgk** [comment]
You can setup the build environment with:
```
mamba create -n build conda-build conda-smithy conda-forge-pinning
conda activate build
```
It's faster that way and also saves CI time (especially for Travis on PowerPC builds).

**Comment by awvwgk** [comment]
Regarding platform and architecture support, should we take a stab at OSX ARM here?

**Comment by certik** [comment]
> Regarding platform and architecture support, should we take a stab at OSX ARM here?

Yes, for sure. I have the new M1 Laptop and it's really fast. I got LFortran working there already. We should get fpm working. Does GFortran work there?

**Comment by awvwgk** [comment]
Conda-forge has a version of GFortran 10 for OSX ARM you could use for testing locally or we just add a migrator and see how far we get with cross-compiling with the current setup.

**Comment by certik** [comment]
Let's just use GFortran 10 natively, that should do it.

**Comment by certik** [comment]
Here is the ARM macOS build for LFortran:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=287582&view=logs&j=ced5d8de-8227-5f3f-33a1-45cf1592c45a

I thought it runs natively, but now when you mentioned it, it is probably cross-compiled. I can't tell the difference from the log!

Either way, we'll see.

**Pull request merged**
